In [ ]:
from openvino import inference_engine as ie
from openvino.inference_engine import IENetwork, IEPlugin
model_xml = './FP32/face-detection-retail-0004.xml'
model_bin = './FP32/face-detection-retail-0004.bin'
plugin_dir = None
import os
import cv2
import numpy as np
assert 'computer_vision_sdk' in os.environ['PYTHONPATH']
OPENVINO_CPU_SO = 'FP32/lib/libcpu_extension.so'

plugin = IEPlugin("CPU", plugin_dirs=plugin_dir)
net = IENetwork.from_ir(model=model_xml, weights=model_bin)

input_blob = next(iter(net.inputs))
out_blob = next(iter(net.outputs))
plugin.add_cpu_extension(OPENVINO_CPU_SO)

exec_net = plugin.load(network=net)
del net

cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 160)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 120)
while 1:
	ret, img = cap.read()
	print(img.shape)

	img = cv2.resize(img, (300, 300), interpolation = cv2.INTER_LINEAR) 
	print(img.shape)
	img2 = np.moveaxis(img, -1, 0)
	img2=np.reshape(img2,(1,3,300,300))
	gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
	res = exec_net.infer(inputs={input_blob: img2})
	output_node_name = list(res.keys())[0]
	res = res[output_node_name]
	print(res[0][0][0][3:])
	print(res.shape)
	#break
	x,y,w,h=res[0][0][0][3:]
	cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)
	

	# for (x,y,w,h) in res[0][0][0][3:]:
	# 	cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
	# 	roi_color = img[y:y+h, x:x+w]
	# img = np.moveaxis(img, -1, 0)
	# img=np.reshape(img,(300,300,3))
	# print(img.shape)
	cv2.imshow('img',img)
	k = cv2.waitKey(30) & 0xff
	if k == 27:
		break

cap.release()
cv2.destroyAllWindows()


/home/aman/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'openvino.inference_engine.ie_api' does not match runtime version 3.7
  return f(*args, **kwds)
/home/aman/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: DeprecationWarning: from_ir() method of IENetwork is deprecated. Please use IENetwork class constructor to create valid IENetwork instance
  del sys.path[0]


(144, 176, 3)
(300, 300, 3)
[0.49290115 0.283448   0.829009   0.8377353 ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.49336952 0.28152162 0.8244578  0.82623667]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.49439442 0.2698123  0.83754313 0.8475905 ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.48985052 0.29568976 0.8293592  0.8404663 ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.4892361  0.30042046 0.8392829  0.84618896]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.49422395 0.30284402 0.83639634 0.84061015]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.4953856  0.30622014 0.83994526 0.8383466 ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.49988568 0.29208875 0.853493   0.8673264 ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.5006308  0.29271394 0.85079867 0.8747693 ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.5054973  0.296831   0.8612737  0.89051974]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.5090747  0.3096087  0.85326135 0.8880552 ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 3

(144, 176, 3)
(300, 300, 3)
[0.56339914 0.32251883 0.91523093 0.8745816 ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.5666736  0.32851276 0.91759855 0.87694025]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.5653895  0.32912105 0.9139898  0.878514  ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.5661757  0.3179723  0.9151863  0.89256406]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.5632319  0.31097484 0.912541   0.8859134 ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.5699039  0.3202664  0.9145213  0.88112974]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.57143474 0.31727576 0.91404545 0.88824034]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.5695027  0.32571846 0.9140483  0.8881486 ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.5724989  0.33512813 0.91484666 0.8867367 ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.5703601  0.32783633 0.9137134  0.8823213 ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.5686449  0.3259548  0.9170449  0.89342904]
(1, 1, 200, 7)
(144, 176, 3)
(300, 3

(144, 176, 3)
(300, 300, 3)
[0.48935324 0.27338108 0.79819447 0.8045647 ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.49031264 0.26727417 0.8075939  0.8053502 ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.49076104 0.27817398 0.8052114  0.7941032 ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.49012312 0.27258545 0.80078197 0.80167204]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.49033183 0.27168128 0.80327433 0.8024521 ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.4903995  0.2789928  0.8075912  0.79595006]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.4876198  0.27340785 0.80609894 0.79716694]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.49214828 0.28388354 0.803872   0.7950835 ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.48827982 0.27674308 0.8122196  0.7942271 ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.48955348 0.28354365 0.7988063  0.8070287 ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 300, 3)
[0.4862755  0.27628362 0.8038841  0.8052219 ]
(1, 1, 200, 7)
(144, 176, 3)
(300, 3